[package]
name = "rust-wps-powerpoint-auto-select"
version = "0.1.0"
edition = "2021"

[dependencies]
yaml-rust2 = "0.9"
chrono = "0.4.38"
winres = "*"

[package.metadata.sprinter.windows]
subsystem = "windows"