name: Building

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: build-debug
      run: cargo build --verbose
    - name: build-release
      run: cargo build --release --verbose

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: rust-wps-powerpoint-auto-select.exe
        path: ./target/*/rust-wps-powerpoint-auto-select.exe
